### ISSUE TITLE
Unable to auto detect root package

### ISSUE THREAD

**Issue by tomwscott** [bodar/jcompilo#4]
When adding a MANIFEST.MF in the META-INF folder under src, jcompilo fails with the error: 

```
BUILD FAILED: com.googlecode.jcompilo.JCompiloException: Unable to auto detect root package
```

Looking at the AutoBuild [source](https://github.com/bodar/jcompilo/blob/master/src/com/googlecode/jcompilo/convention/AutoBuild.java) the exception gets thrown if there is more than one folder under the specified src directory.  The README states that the META-INF folder is optional but does it require configuration if you choose to include it? Should I provide my own Build.java rather than using the AutoBuild conventions?

```
jcompilo version: 2.3
java version "1.8.0_20"
Java(TM) SE Runtime Environment (build 1.8.0_20-b26)
Java HotSpot(TM) 64-Bit Server VM (build 25.20-b23, mixed mode)
```

**Comment by serverbodarcom** [comment]
Please try version 2.25 https://github.com/bodar/jcompilo/releases/tag/2.25

**Comment by tomwscott** [comment]
Roger that, works as expected :)
